name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout Code
        run: echo "Checking out the code"
      - name: Printing Folders
        run: ls -d */
