name: 08 - Using Variables

env:
  WORKFLOW_VAR: 'I am a workflow env variable'
  OVERWRITTEN: 'I will be overwritten'

on:
  push:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env variable'
      OVERWRITTEN: 'I have been overwritten at the job level'
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step env variable'
          STEP_VAR2: 'I am another step env variable'
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var 2: ${{ env.STEP_VAR2 }}"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten var: ${{ env.OVERWRITTEN }}"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "Step evn var: ${{ env.OVERWRITTEN}}"
