name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will pring if previous steps succeed"
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any prvious steps fail"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will print if any prvious steps fail"
      - name: I will execute when canceled
        if: ${{ cancelled() }}
        run: echo "I will print if any prvious steps fail"
